<?php

namespace App\Support;

/**
 * The ONE definition of the installed app's launch imagery.
 *
 * 🚨 A file under `public/` is NOT served on the app domain — measured, and the
 * reason every icon in `routes/web.php` comes through a proxy route reading from
 * `resources/proxy/`. The launch images follow the same rule: the PNGs live in
 * `resources/proxy/splash/` and are served by `ios.splash`. Never point an
 * `apple-touch-startup-image` at a bare `/public` path.
 *
 * 🚨 iOS matches a startup image on EXACT device metrics. A tag whose media query
 * does not match, or whose image is not the exact device pixel size, is ignored
 * outright — it does not scale and it does not fall back. Every entry below was
 * previously pointed at `apple-touch-icon.png` (512x512), so the whole set was
 * inert and the installed app launched to a blank screen.
 *
 * The artwork is regenerated by the build script documented in
 * `docs/implementations/` — filenames are derived, never typed: a device's file
 * is (css width x dpr) by (css height x dpr).
 */
class PwaSplash
{
    /**
     * CSS width, CSS height and device pixel ratio of every supported device.
     * Portrait only: the manifest declares `orientation: portrait`, and a
     * landscape set would double the payload shipped inside the Lambda.
     *
     * @var array<int, array{w: int, h: int, dpr: int}>
     */
    public const LAUNCH_IMAGES = [
        // iPhone
        ['w' => 320, 'h' => 568, 'dpr' => 2],   // SE (1st gen)
        ['w' => 375, 'h' => 667, 'dpr' => 2],   // 6 / 7 / 8 / SE 2 / SE 3
        ['w' => 414, 'h' => 896, 'dpr' => 2],   // XR / 11
        ['w' => 375, 'h' => 812, 'dpr' => 3],   // X / XS / 11 Pro / 12 mini / 13 mini
        ['w' => 390, 'h' => 844, 'dpr' => 3],   // 12 / 12 Pro / 13 / 13 Pro / 14
        ['w' => 393, 'h' => 852, 'dpr' => 3],   // 14 Pro / 15 / 15 Pro / 16
        ['w' => 402, 'h' => 874, 'dpr' => 3],   // 16 Pro
        ['w' => 414, 'h' => 736, 'dpr' => 3],   // 6+ / 7+ / 8+
        ['w' => 414, 'h' => 896, 'dpr' => 3],   // XS Max / 11 Pro Max
        ['w' => 428, 'h' => 926, 'dpr' => 3],   // 12 Pro Max / 13 Pro Max / 14 Plus
        ['w' => 430, 'h' => 932, 'dpr' => 3],   // 14 Pro Max / 15 Plus / 15 Pro Max / 16 Plus
        ['w' => 440, 'h' => 956, 'dpr' => 3],   // 16 Pro Max

        // iPad
        ['w' => 744, 'h' => 1133, 'dpr' => 2],  // mini (6th gen)
        ['w' => 768, 'h' => 1024, 'dpr' => 2],  // 9.7"
        ['w' => 810, 'h' => 1080, 'dpr' => 2],  // 10.2"
        ['w' => 820, 'h' => 1180, 'dpr' => 2],  // Air 10.9"
        ['w' => 834, 'h' => 1112, 'dpr' => 2],  // Pro 10.5"
        ['w' => 834, 'h' => 1194, 'dpr' => 2],  // Pro 11"
        ['w' => 1024, 'h' => 1366, 'dpr' => 2], // Pro 12.9"
    ];

    /** Basename of the generated PNG for a device entry, e.g. `1290x2796`. */
    public static function fileFor(array $device): string
    {
        return ($device['w'] * $device['dpr']).'x'.($device['h'] * $device['dpr']);
    }

    /**
     * Whether a requested basename is one this app actually publishes.
     *
     * ⚠️ The route resolves against THIS set, never against whatever the request
     * asked for — the filename becomes a filesystem path, and a value taken from
     * the URL must never reach one.
     */
    public static function knows(string $file): bool
    {
        foreach (self::LAUNCH_IMAGES as $device) {
            if (self::fileFor($device) === $file) {
                return true;
            }
        }

        return false;
    }
}
