import { Head } from "@inertiajs/react";
import Guest from "@/Layouts/GuestLayout";
import LegalLayout from "@/Layouts/LegalLayout";

export default function CreatorAgreement(props) {
    const { auth, user } = props;
    return (
        <Guest auth={auth?.user} user={user}>
            <Head title="Creator Agreement" />
            <LegalLayout activePage="CreatorAgreement">
                <div className="mx-auto p-8 md:p-12">
                    <h1 className="text-3xl md:text-4xl font-black text-pink-600 mb-8 uppercase tracking-tighter">
                        Creator Agreement
                    </h1>
                    <div className="prose prose-pink max-w-none">
                        <h2 className="text-xl md:text-2xl font-bold text-gray-900 mt-8 mb-4">SPENNY PIGGY</h2>
<h2 className="text-xl md:text-2xl font-bold text-gray-900 mt-8 mb-4">CREATOR AGREEMENT</h2>
<p className="mb-4 text-gray-700 leading-relaxed">Issue Date: 23 April 2026</p>
<p className="mb-4 text-gray-700 leading-relaxed">Social Vortex Limited (England & Wales)  ·  Company No. 15233693</p>
<p className="mb-4 text-gray-700 leading-relaxed">Registered Office: 55 Colmore Row, Birmingham, B3 2AA, United Kingdom  ·  VAT: GB452012540</p>
<p className="mb-4 text-gray-700 leading-relaxed">US Entity: Social Vortex, Inc (Delaware, USA)</p>
<p className="mb-4 text-gray-700 leading-relaxed">1.  Scope and Relationship</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.1  Application</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.1.1  This Creator Agreement applies to any user who creates, operates, or uses a Creator account or any monetisation feature on Spenny Piggy.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.1.2  This Agreement supplements the Terms of Service and forms part of the Platform Legal Framework. Where there is any inconsistency between this Agreement and any other document within the Platform Legal Framework, the provision most protective of Spenny Piggy’s legal and operational position shall apply to the extent permitted by law.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.2  Independent Status</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.2.1  You acknowledge and agree that:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	you are an independent user of the Platform;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	you are not an employee, agent, contractor, or representative of Spenny Piggy; and</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	you have no authority to bind or act on behalf of Spenny Piggy in any capacity.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.3  Merchant of Record</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.3.1  You acknowledge and agree that you act as the Merchant of Record for all creator-led transactions processed through the Platform. Except where explicitly stated otherwise by Spenny Piggy in writing for a specific feature or flow, you are solely responsible for:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	setting and communicating pricing;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	the fulfilment of any content, goods, or services offered;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	the legality of your offerings;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	handling customer queries and complaints; and</div>
<div className="ml-6 mb-2 text-gray-700">(v)	tax compliance in respect of your earnings.</div>
<p className="mb-4 text-gray-700 leading-relaxed">2.  Onboarding, Verification and Eligibility</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">2.1  Verification Requirements</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">2.1.1  You must complete all onboarding requirements before receiving payments through the Platform. These requirements include, without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	identity verification;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	payment account setup;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	submission of required tax information; and</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	completion of account security checks.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">2.1.2  Spenny Piggy reserves the right to request enhanced due diligence at any time, including without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	source of funds information;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	business or commercial information;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	ownership and beneficial interest information; and</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	supporting documentary evidence.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">2.2  Ongoing Accuracy</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">2.2.1  You must ensure that all information provided to Spenny Piggy remains accurate, complete, and up to date at all times. Spenny Piggy reserves the right to pause or restrict your account where information is found to be outdated, inconsistent, or unverifiable.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">2.3  Security</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">2.3.1  You must maintain all security measures required by Spenny Piggy from time to time, including without limitation two-factor authentication and device verification. Failure to maintain such measures may result in account restrictions being applied.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">3.  Merchant of Record Responsibilities</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.1  Legal Responsibility</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.1.1  As Merchant of Record, you are solely responsible for:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	ensuring the legality of all offers, products, and services made available through your account;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	the accuracy and transparency of your pricing structure;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	the fulfilment of all commitments made to Supporters;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	the accuracy of all representations made in connection with your offerings;</div>
<div className="ml-6 mb-2 text-gray-700">(v)	handling refund requests in accordance with applicable law; and</div>
<div className="ml-6 mb-2 text-gray-700">(vi)	compliance with all applicable consumer protection laws and regulations.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.2  Permitted Use</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.2.1  You must only offer lawful products and services through the Platform, using compliant monetisation features, and must ensure that all offers are transparent and accurately represented. Permitted monetisation features include, without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	subscriptions;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	paid messages;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	paid tasks;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	timed payments;</div>
<div className="ml-6 mb-2 text-gray-700">(v)	incentives; and</div>
<div className="ml-6 mb-2 text-gray-700">(vi)	leaderboard-based features.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.3  Disclosures</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.3.1  You must clearly communicate to Supporters, prior to any transaction being completed:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	a description of what the Supporter will receive;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	applicable fulfilment timelines;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	any conditions or restrictions attached to the offering; and</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	your refund approach in respect of the relevant transaction type.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.3.2  The minimum standards applicable to your Creator obligations are further described in Schedule 3 (Compliance Reminders) to this Agreement.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">4.  Content and Conduct Standards</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.1  Content Responsibility</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.1.1  You are solely responsible for all content you publish through the Platform. You must not:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	mislead users in connection with any offering or interaction;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	engage in coercion or the use of threats or undue pressure;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	provide unlawful or prohibited products, services, or interactions; or</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	engage in any conduct that is harmful, abusive, or in breach of these Terms.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.2  Payment Conduct</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.2.1  You must not force, pressure, or otherwise improperly induce payments from any user. You must not create deceptive payment flows or take any action to bypass Platform payment systems. All monetisation features must be operated in a manner that is consensual, transparent, and lawful at all times.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.3  Platform Moderation</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.3.1  Spenny Piggy reserves the right, at its sole discretion, to review, remove, or restrict any content, disable monetisation features, and require you to make changes to any content or offering. Such actions may be taken without prior notice where Spenny Piggy considers them necessary for compliance, risk management, or the protection of users or the Platform.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.3.2  The conduct and content standards that may give rise to immediate restriction are set out in Schedule 2 (Immediate Restriction Triggers) to this Agreement.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">5.  Fees, Pricing and Earnings</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.1  Pricing Model</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.1.1  You are responsible for setting the prices applicable to your offerings, unless otherwise specified by Spenny Piggy. Under the current model, Platform fees are charged to Supporters at checkout, and you receive your listed amount, subject to:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	applicable reserve deductions;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	refunds and reversals;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	chargeback deductions; and</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	any other deductions applied in accordance with these Terms or the Payments, Payouts & Reserves Policy.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.2  Creator Charges</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.2.1  Spenny Piggy reserves the right to apply creator-facing charges, which may include without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	subscription or account fees;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	payout fees;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	verification fees; and</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	administrative fees.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.2.2  Such charges will be disclosed to you at the point of activation or billing.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.3  Set-Off Rights</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.3.1  You expressly authorise Spenny Piggy to deduct from your available balance, earnings, or reserve funds any amounts arising from refunds, chargebacks, negative balances, or Platform losses attributable to your account. These rights are without prejudice to any other recovery rights available to Spenny Piggy under the Terms of Service or applicable law.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">6.  Payouts, Reserves and Balances</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">6.1  Payout Timing</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">6.1.1  The standard payout cycle operates on a weekly basis, with earnings calculated from Friday to Thursday and paid on the following Friday. Payouts are not guaranteed on any specific date and remain subject to review in accordance with the Payments, Payouts & Reserves Policy.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">6.2  Payout Controls</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">6.2.1  Spenny Piggy reserves the right, at its sole discretion, to delay, hold, apply reserves to, reverse, or suspend any payout at any time. The risk signals that may give rise to increased reserve levels or enhanced payout controls are set out in Schedule 4 (Increased Risk Signals) to this Agreement.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">6.3  Negative Balances</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">6.3.1  Where your account balance becomes negative, you remain liable for the full amount of that negative balance. Spenny Piggy reserves the right to recover the outstanding amount by deduction from future earnings or by requiring direct repayment from you. The enforcement outcomes that may apply in such circumstances are set out in Schedule 5 (Enforcement Outcomes) to this Agreement.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">7.  Refunds, Complaints and Disputes</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">7.1  Responsibility</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">7.1.1  As Merchant of Record, you are responsible for handling all complaints, fulfilment issues, and support requests arising in connection with your Creator Content. You must engage with such matters promptly and in good faith.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">7.2  Evidence Requirements</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">7.2.1  You must maintain sufficient records to evidence your compliance with this Agreement, including without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	copies of offer details and descriptions;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	timestamps relating to transactions and communications;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	communication logs with Supporters; and</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	evidence of fulfilment.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">7.2.2  The full list of records you are required to retain is set out in Schedule 1 (Creator Evidence Checklist) to this Agreement.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">7.3  Cooperation</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">7.3.1  You must cooperate fully with Spenny Piggy in connection with any dispute, investigation, or compliance review. Spenny Piggy reserves the right to recover from you any chargeback losses, fees, penalties, and operational costs arising from or in connection with transactions on your account.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">8.  Wishlist and Commerce Flows</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.1  Retail Fulfilment</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.1.1  Where physical goods are involved in a transaction, fulfilment is handled by independent third-party retailers. Spenny Piggy is not responsible for the fulfilment, delivery, or quality of physical goods.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.2  Accuracy</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.2.1  You must not misrepresent any product or mislead users in connection with any product-linked or wishlist transaction. All product descriptions and representations must be accurate and not misleading.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.3  Operational Control</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.3.1  Spenny Piggy reserves the right to reroute transactions, issue credits, or otherwise intervene in fulfilment flows where it considers such action necessary for the protection of users, payment processors, or the Platform.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">9.  Taxes and Compliance</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">9.1  You are solely responsible for determining, reporting, and paying all taxes, fulfilling all reporting obligations, and complying with all applicable regulatory requirements arising from your use of the Platform and your earnings as a Creator.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">9.2  Spenny Piggy may request tax documentation from you at any time and reserves the right to withhold payouts until satisfactory evidence of compliance has been provided.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">10.  Suspension, Termination and Enforcement</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.1  Suspension and Termination</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.1.1  Spenny Piggy reserves the right to suspend or terminate account access, hold funds, and continue any ongoing investigation at its sole discretion and at any time, with or without prior notice. The enforcement outcomes that may apply are set out in Schedule 5 (Enforcement Outcomes) to this Agreement.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.2  Minimum Standards</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.2.1  You must at all times:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	respond to Supporters in a timely manner;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	deliver the content, goods, or services you have committed to provide; and</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	maintain accurate and up-to-date listings.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.2.2  Failure to meet these minimum standards may give rise to account restrictions, reserve increases, or termination in accordance with Schedule 5 (Enforcement Outcomes).</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.3  Off-Platform Conduct</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.3.1  Spenny Piggy reserves the right to take action in respect of off-platform behaviour where such behaviour constitutes a fraud indicator, presents a reputational risk to the Platform, or is otherwise inconsistent with these Terms or applicable law.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.4  Audit Rights</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.4.1  Spenny Piggy reserves the right to request transaction records, fulfilment evidence, and compliance documentation from you at any time. Spenny Piggy may share relevant data with payment processors and legal or regulatory authorities where required.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">Schedule 1 — Creator Evidence Checklist</p>
<p className="mb-4 text-gray-700 leading-relaxed">For the purposes of clause 7.2, you are required to retain the following records:</p>
<div className="ml-6 mb-2 text-gray-700">(i)	copies of all offers, listings, and promotional materials;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	timestamps relating to transactions and communications;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	all communications with Supporters relevant to transactions;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	proof of delivery or fulfilment for each transaction; and</div>
<div className="ml-6 mb-2 text-gray-700">(v)	records of all refunds issued.</div>
<p className="mb-4 text-gray-700 leading-relaxed">Schedule 2 — Immediate Restriction Triggers</p>
<p className="mb-4 text-gray-700 leading-relaxed">For the purposes of clause 4.3.2, the following conduct may give rise to immediate account restriction, without limitation:</p>
<div className="ml-6 mb-2 text-gray-700">(i)	misrepresentation of any offering or product;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	coercion or undue pressure applied to any Supporter;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	any attempt to bypass Platform fees or payment systems;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	submission of false or misleading verification information; and</div>
<div className="ml-6 mb-2 text-gray-700">(v)	failure to respond to Supporters or to Spenny Piggy within a reasonable period.</div>
<p className="mb-4 text-gray-700 leading-relaxed">Schedule 3 — Compliance Reminders</p>
<p className="mb-4 text-gray-700 leading-relaxed">For the purposes of clause 3.3.2, the following are minimum compliance expectations applicable to all Creators:</p>
<div className="ml-6 mb-2 text-gray-700">(i)	keep all account information and listing details accurate and up to date;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	respond to Supporters and to Spenny Piggy promptly;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	ensure all pricing is clear, accurate, and not misleading; and</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	retain records in accordance with Schedule 1 to this Agreement.</div>
<p className="mb-4 text-gray-700 leading-relaxed">Schedule 4 — Increased Risk Signals</p>
<p className="mb-4 text-gray-700 leading-relaxed">For the purposes of clause 6.2.1, the following are examples of risk signals that may give rise to enhanced payout controls or increased reserve levels, without limitation:</p>
<div className="ml-6 mb-2 text-gray-700">(i)	rapid or unexplained transaction growth;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	spikes in complaints or dispute rates;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	identity inconsistencies or verification concerns; and</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	flags raised by payment processors or fraud detection systems.</div>
<p className="mb-4 text-gray-700 leading-relaxed">Schedule 5 — Enforcement Outcomes</p>
<p className="mb-4 text-gray-700 leading-relaxed">For the purposes of clauses 6.3.1 and 10.1.1, the following enforcement outcomes may be applied by Spenny Piggy at its sole discretion, without limitation:</p>
<div className="ml-6 mb-2 text-gray-700">(i)	restriction of account features;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	increase of reserve levels;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	delay or suspension of payouts;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	temporary or permanent account suspension;</div>
<div className="ml-6 mb-2 text-gray-700">(v)	termination of account access; and</div>
<div className="ml-6 mb-2 text-gray-700">(vi)	initiation of debt recovery proceedings.</div>
<p className="mb-4 text-gray-700 leading-relaxed">These Terms were last updated on 23 April 2026.</p>
<p className="mb-4 text-gray-700 leading-relaxed">© 2026 Social Vortex Limited, trading as Spenny Piggy. All rights reserved.</p>
                    </div>
                </div>
            </LegalLayout>
        </Guest>
    );
}
