import { Head } from "@inertiajs/react";
import Guest from "@/Layouts/GuestLayout";
import LegalLayout from "@/Layouts/LegalLayout";

export default function PaymentsPolicy(props) {
    const { auth, user } = props;
    return (
        <Guest auth={auth?.user} user={user}>
            <Head title="Reserves and Payments Policy" />
            <LegalLayout activePage="PaymentsPolicy">
                <div className="mx-auto p-8 md:p-12">
                    <h1 className="text-3xl md:text-4xl font-black text-pink-600 mb-8 uppercase tracking-tighter">
                        Reserves and Payments Policy
                    </h1>
                    <div className="prose prose-pink max-w-none">
                        <h2 className="text-xl md:text-2xl font-bold text-gray-900 mt-8 mb-4">SPENNY PIGGY</h2>
<h2 className="text-xl md:text-2xl font-bold text-gray-900 mt-8 mb-4">PAYMENTS, PAYOUTS & RESERVES POLICY</h2>
<p className="mb-4 text-gray-700 leading-relaxed">Issue Date: 23 April 2026</p>
<p className="mb-4 text-gray-700 leading-relaxed">Social Vortex Limited (England & Wales)  ·  Company No. 15233693</p>
<p className="mb-4 text-gray-700 leading-relaxed">Registered Office: 55 Colmore Row, Birmingham, B3 2AA, United Kingdom  ·  VAT: GB452012540</p>
<p className="mb-4 text-gray-700 leading-relaxed">US Entity: Social Vortex, Inc (Delaware, USA)</p>
<p className="mb-4 text-gray-700 leading-relaxed">1.  Platform Overview and Role</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.1  Spenny Piggy is a technology platform that enables transactions between users. It is not a bank, financial institution, payment service provider, or regulated entity in respect of the transactions it facilitates.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.2  For all creator-led transactions processed via the Platform, the Creator acts as the Merchant of Record. All payments are processed via third-party payment providers and are subject to platform review, fraud checks, dispute monitoring, and compliance controls.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.3  In connection with transactions conducted through the Platform, Spenny Piggy:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	facilitates transactions between users;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	applies Platform Fees at checkout; and</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	manages payout timing and risk controls.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">1.4  Spenny Piggy does not act as a bank or financial institution in respect of any funds held or disbursed through the Platform.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">2.  Payment Processing</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">2.1  All payments are processed through third-party payment providers. Payments are made to Creators as Merchant of Record and are subject to the rules and controls of the applicable payment processor and to Spenny Piggy’s own risk and compliance review.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">2.2  For the purposes of risk assessment and fraud prevention, Spenny Piggy may monitor, without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	transaction velocity;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	payment patterns;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	dispute rates;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	account behaviour; and</div>
<div className="ml-6 mb-2 text-gray-700">(v)	device and geographic signals.</div>
<p className="mb-4 text-gray-700 leading-relaxed">3.  Payout Schedule</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.1  Creators are paid on a weekly payout cycle. The standard earnings period runs from Friday to Thursday, with the standard payout day being the following Friday.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">3.2  Payouts are not guaranteed on any specific date and remain subject to:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	account status;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	dispute activity;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	applicable reserve requirements;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	compliance checks; and</div>
<div className="ml-6 mb-2 text-gray-700">(v)	payment processor settlement timelines.</div>
<p className="mb-4 text-gray-700 leading-relaxed">4.  Payment Reviews and Delays</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.1  For the purposes of protecting users, payment partners, and the integrity of the Platform, Spenny Piggy reserves the right to delay, pause, split, reverse, or refuse any payout at its sole discretion.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">4.2  Such action may be taken where Spenny Piggy detects or reasonably suspects, without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	unusual payment activity;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	elevated dispute or refund risk;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	sudden increases in transaction volume;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	suspected fraud or abuse;</div>
<div className="ml-6 mb-2 text-gray-700">(v)	policy violations;</div>
<div className="ml-6 mb-2 text-gray-700">(vi)	missing or incomplete verification;</div>
<div className="ml-6 mb-2 text-gray-700">(vii)	linked or associated account risk;</div>
<p className="mb-4 text-gray-700 leading-relaxed">(viii)	moderation concerns; or</p>
<div className="ml-6 mb-2 text-gray-700">(ix)	legal or regulatory requests.</div>
<p className="mb-4 text-gray-700 leading-relaxed">5.  Reserve Policy</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.1  To manage payment risk, Spenny Piggy may apply a rolling reserve to any Creator account. A reserve constitutes the temporary withholding of a percentage of earnings prior to disbursement, pending release in accordance with this Policy.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.2  Spenny Piggy applies reserves in accordance with the following standard framework, based on each account’s risk classification:</h3>
<p className="mb-4 text-gray-700 leading-relaxed">Account Classification</p>
<p className="mb-4 text-gray-700 leading-relaxed">Reserve Rate</p>
<p className="mb-4 text-gray-700 leading-relaxed">Holding Period</p>
<p className="mb-4 text-gray-700 leading-relaxed">Established accounts – strong history, no material risk indicators</p>
<p className="mb-4 text-gray-700 leading-relaxed">0%</p>
<h2 className="text-xl md:text-2xl font-bold text-gray-900 mt-8 mb-4">N/A</h2>
<p className="mb-4 text-gray-700 leading-relaxed">New or recently activated accounts</p>
<p className="mb-4 text-gray-700 leading-relaxed">10%</p>
<p className="mb-4 text-gray-700 leading-relaxed">30 days</p>
<p className="mb-4 text-gray-700 leading-relaxed">Moderate risk – rapid growth, unusual volume, incomplete history</p>
<p className="mb-4 text-gray-700 leading-relaxed">15%</p>
<p className="mb-4 text-gray-700 leading-relaxed">60 days</p>
<p className="mb-4 text-gray-700 leading-relaxed">Elevated risk – increased disputes, high refund activity, abnormal patterns</p>
<p className="mb-4 text-gray-700 leading-relaxed">20%</p>
<p className="mb-4 text-gray-700 leading-relaxed">90 days</p>
<p className="mb-4 text-gray-700 leading-relaxed">High risk – suspected fraud, chargeback exposure, compliance concerns, platform abuse</p>
<p className="mb-4 text-gray-700 leading-relaxed">Up to 30% or full hold</p>
<p className="mb-4 text-gray-700 leading-relaxed">As determined by Spenny Piggy</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.3  In addition to the standard framework set out above, Spenny Piggy may apply a full temporary hold on all funds where required for:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	the purposes of an ongoing investigation;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	compliance with payment partner requirements; or</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	the fulfilment of legal obligations.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">5.4  Spenny Piggy reserves the right to apply, modify, or remove reserves at any time based on updated risk assessment, without prior notice to the Creator.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">6.  Reserve Release</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">6.1  Rolling reserve amounts shall be released automatically upon expiry of the applicable holding period, subject to the following conditions being met:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	the account remains compliant with these Terms and all associated Platform policies; and</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	no new disputes, risk events, or compliance concerns have arisen during the holding period.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">6.2  The applicable holding periods are 30 days, 60 days, and 90 days, as determined by the Creator’s risk classification in accordance with clause 5.2.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">6.3  Spenny Piggy reserves the right to reduce, extend, increase, or remove any reserve at any time based on updated risk assessment. Where risk persists beyond any stated holding period, reserved funds may be held for such further duration as Spenny Piggy considers necessary.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">7.  Chargebacks, Refunds and Offsets</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">7.1  Spenny Piggy reserves the right to deduct from a Creator’s available balance, earnings, or reserve funds any amounts arising from or in connection with:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	chargebacks;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	refunds;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	transaction reversals;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	retailer adjustments; and</div>
<div className="ml-6 mb-2 text-gray-700">(v)	Platform losses attributable to the relevant Creator account.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">7.2  Where deductions result in a negative balance on a Creator’s account:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	the negative balance may be carried forward; and</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	future payouts may be reduced or withheld until the negative balance is recovered in full.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">7.3  The foregoing rights are without prejudice to any other recovery rights available to Spenny Piggy under the Terms of Service or applicable law.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">8.  Physical Goods (Wishlist and Storefront Purchases)</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.1  Where a Supporter purchases a physical item through the Platform, fulfilment of that item is handled by an independent third-party retailer via Spenny Piggy’s commerce infrastructure partners.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.2  The relevant retailer is solely responsible for:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	shipping and delivery;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	returns and refund decisions; and</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	product quality and stock availability.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">8.3  Spenny Piggy accepts no responsibility or liability in respect of:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	delivery delays;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	lost or damaged items;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	stock availability; or</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	retailer refund decisions.</div>
<p className="mb-4 text-gray-700 leading-relaxed">9.  Moderation and Payment Controls</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">9.1  Spenny Piggy operates an interconnected content and payment control framework. Where content or account activity gives rise to risk, Spenny Piggy may, without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	pause listings;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	restrict checkout functionality;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	delay payouts;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	apply reserves; or</div>
<div className="ml-6 mb-2 text-gray-700">(v)	suspend accounts.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">9.2  Such action may be taken where Spenny Piggy identifies, without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	misrepresentation;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	prohibited activity;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	policy violations; or</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	unsafe or non-compliant behaviour.</div>
<p className="mb-4 text-gray-700 leading-relaxed">10.  Account Restrictions</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">10.1  Spenny Piggy reserves the right to restrict, suspend, or terminate account features and access, at its sole discretion, where:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	a user has breached the Terms of Service or any associated Platform policy;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	fraud risk is detected or reasonably suspected;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	compliance checks are required; or</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	the integrity of the payment infrastructure is considered to be at risk.</div>
<p className="mb-4 text-gray-700 leading-relaxed">11.  Risk Monitoring</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">11.1  Spenny Piggy operates a continuous risk monitoring framework. Risk signals assessed by Spenny Piggy may include, without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	rapid transaction growth;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	high-value transactions;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	repeat payment patterns;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	dispute frequency;</div>
<div className="ml-6 mb-2 text-gray-700">(v)	cross-account behaviour;</div>
<div className="ml-6 mb-2 text-gray-700">(vi)	geographic inconsistencies; and</div>
<div className="ml-6 mb-2 text-gray-700">(vii)	disproportionate account age relative to transaction volume.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">11.2  Risk determinations are made by reference to the overall account profile and are not limited to any single signal or indicator.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">12.  Record Keeping and Audit</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">12.1  Spenny Piggy may retain records including, without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	transaction data;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	payout history;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	reserve history;</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	dispute evidence; and</div>
<div className="ml-6 mb-2 text-gray-700">(v)	moderation actions.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">12.2  Such records may be used for the purposes of compliance, audit, dispute resolution, and fulfilment of payment processor requirements.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">13.  Security and Account Integrity</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">13.1  Spenny Piggy may implement security controls including, without limitation:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	account verification procedures;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	login monitoring;</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	device checks; and</div>
<div className="ml-6 mb-2 text-gray-700">(iv)	automated fraud detection systems.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">13.2  Where account compromise is suspected, Spenny Piggy may, at its sole discretion:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	pause payouts;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	lock account access; and</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	require re-verification before access or payouts are restored.</div>
<p className="mb-4 text-gray-700 leading-relaxed">14.  Payment Partner and Platform Protection</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">14.1  Spenny Piggy reserves the right to apply controls that exceed standard operational parameters where it considers such measures necessary to:</h3>
<div className="ml-6 mb-2 text-gray-700">(i)	protect its relationships with payment processors;</div>
<div className="ml-6 mb-2 text-gray-700">(ii)	maintain the stability and integrity of the Platform; or</div>
<div className="ml-6 mb-2 text-gray-700">(iii)	prevent financial loss to the Platform or its payment partners.</div>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">14.2  Spenny Piggy is not required to disclose its internal risk thresholds, scoring methodologies, or the specific basis for any individual risk determination.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">15.  Policy Updates</p>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">15.1  This Policy forms part of the Platform Legal Framework and is incorporated by reference into the Spenny Piggy Terms of Service. It may be updated at any time to reflect changes in fraud trends, legal or regulatory requirements, payment partner rules, or operational improvements.</h3>
<h3 className="text-lg font-semibold text-gray-800 mt-6 mb-3">15.2  Continued use of the Platform following the publication of an updated Policy constitutes acceptance of the revised terms. Users are responsible for reviewing this Policy periodically.</h3>
<p className="mb-4 text-gray-700 leading-relaxed">These Terms were last updated on 23 April 2026.</p>
<p className="mb-4 text-gray-700 leading-relaxed">© 2026 Social Vortex Limited, trading as Spenny Piggy. All rights reserved.</p>
                    </div>
                </div>
            </LegalLayout>
        </Guest>
    );
}
